parent-name: @parent.name@
parent-version: @parent.version@
server-name: @project.name@
server-version: @project.version@
build: @buildNumber@
buildDateTime: @timestamp@

spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
spring.datasource.username: chris
spring.datasource.password: abcABC123!@#
spring.datasource.driver-class-name: com.mysql.jdbc.Driver