application.name: @project.name@
application.title: TDS Messenger
application.organization: Technical Development Solutions
application.version: @project.version@
#application.buildNumber: @buildNumber@
application.buildDateTime: @timestamp@

#spring.datasource.url: jdbc:mysql://ubuntu-filekit-01:3306/seed
#spring.datasource.username: chris
#spring.datasource.password: abcABC123!@#
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver

elasticsearch.host: localhost
elasticsearch.username: elastic
elasticsearch.password: O15IYlLhFF3ok17QPEhi

#driverClassName: org.sqlite.JDBC
#url: jdbc:sqlite:memory:myDb?cache=shared
#username: sa
#password: sa
#hibernate.dialect: com.techdevsolutions.shared.dao.sqlite.SQLiteDialect
#hibernate.hbm2ddl.auto: createDocument-drop
#hibernate.show_sql: true

files.root.directory: /Users/chris/spring-boot-tools-files